version: '2'
services:
  lemon-ng:
    build: lemon-ng
    volumes:
      - ./lemon-ng/conf:/var/lib/lemonldap-ng/conf
      - ./lemon-ng/sites:/etc/lemonldap-ng
    ports:
     - "80:80"
     - "443:443"
    networks:
      default:
        aliases: 
          - auth.example.com
          - manager.example.com
          - reload.example.com
  php:
    build: apache-php-dev
    volumes:
      - /home/fred/Development/doc-depot:/var/www/html
      - ./apache-php-dev/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    labels:
      - "nature=binaries"
    ports:
      - "8080:80"
      - "8443:443"    
    depends_on:
      - mysql
    privileged: true
    extra_hosts:
      - "127.0.0.1:dd.example.com"
    networks:
      default:
        aliases: 
          - php
          - dd.example.com

  mysql:
    image: mysql
    build:  doc-depot-mysql
    labels:
      - "nature=data"
    volumes:
      - dd-mysql-datavol:/var/lib/mysql
      - ./doc-depot-mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=azerty
      - MYSQL_DATABASE=docdepot
      - MYSQL_USER=docdepot
      - MYSQL_PASSWORD=docdepot
    ports:
      - "3306:3306"
    #entrypoint: 
    #   - bash
    #   - /usr/local/bin/docker-entrypoint.sh
    networks:
      default:
        aliases: 
          - mysql
volumes:
  dd-mysql-datavol:
networks:
  default: